name: Expo Publish on Master
on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Install and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout Repostiory
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: 6.x
          token: ${{ secrets.EXPO_TOKEN }}
          expo-cache: true

      - name: Install dependencies
        run: yarn

      - name: Publish update
        run: expo publish --release-channel master
